COMP: Need to use vector for non-pod array
ANTS/Examples/ImageMath.cxx:9747:37: error: variable length array of
non-POD element type 'typename ImageType::Pointer' (aka
  'SmartPointer<Self>')